blank_issues_enabled: true
contact_links:
  - name: 🎥 Visual Effects Video Playlist 
    url: https://www.youtube.com/playlist?list=PLEwYhelKHmig6ttzH0nRL3OOQsGLtVrtX
    about: View the Visual Effects examples playlist on YouTube